volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

services:
  nextapp:
    networks:
      - app-network
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: next.debug.dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:4000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - flaskapp

  flaskapp:
    networks:
      - app-network
    build:
      context: ./backend
      dockerfile: flask.debug.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - USER_FERNET_KEY=${USER_FERNET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - PLACES_API_KEY=${PLACES_API_KEY}
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
      - GENAI_API_KEY=${GENAI_API_KEY}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - NEXT_PUBLIC_URL=http://localhost:3000
    command: ["python","-u", "backend/app.py"]
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  db:
    networks:
      - app-network
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tests:
    build:
      context: ./tests
      dockerfile: tests.dockerfile
    environment:
      # Ensure absolute imports work by pointing PYTHONPATH to /app (the project root)
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - USER_FERNET_KEY=${USER_FERNET_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
      - ./.env:/app/.env
    command: ["pytest", "tests"]
    depends_on:
      - db
      - flaskapp
    profiles:
      - tests