services:
  #nextjs service
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - flaskapp
  
  # flask service
  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - FLASK_ENV=development
      - USER_FERNET_KEY=${USER_FERNET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - PLACES_API_KEY=${PLACES_API_KEY}
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
    command: ["python","-u", "backend/app.py"]
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  # db service
  db:
    container_name: db
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Test service to run pytest in the full environment
  tests:
    container_name: tests
    build:
      context: ./tests
      dockerfile: tests.dockerfile
    environment:
      # Ensure absolute imports work by pointing PYTHONPATH to /app (the project root)
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - USER_FERNET_KEY=${USER_FERNET_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
      - ./.env:/app/.env
    command: ["pytest", "tests"]
    depends_on:
      - db
      - flaskapp
    profiles:
      - tests

volumes:
  pgdata: {}