name: Run Tests in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Start Containers
        run: |
          docker compose up --build -d nextapp

      - name: Run Tests Inside Docker
        run: |
          docker-compose run --rm tests

      - name: Stop and Remove Containers
        run: docker-compose down